### PR TITLE
Feed min usd slider

### PR DESCRIPTION
**Pull request by shan8851**
# Description

Adding feed page min usd slider component

---

Fixes # (issue)
[FE-944](https://uniwhales.atlassian.net/browse/FE-944?atlOrigin=eyJpIjoiNGY3YzE0M2UzOWE1NGQ0YTkzZjg4OWY1OTM5MWI4NDIiLCJwIjoiaiJ9)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:
* Hardware: Android/iphone/macbook/pc/laptop

## Was this feature tested on all the browsers?

- [x] Chrome/Brave
- [ ] Firefox
- [ ] Safari 

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have tested my changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Storybook covers all new/pre-existing variations without need to change controls to test it
- [x] I have upgraded version in package.json
- [x] I have assigned QA and Reviewers
- [x] I have labeled the PR accordingly
- [ ] I have updated time spent in my jira ticket
- [ ] Build succeeded

---

## Notes for Devs

[FE-944]: https://uniwhales.atlassian.net/browse/FE-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by shan8851** [comment]
Screenshot 2023-02-20 at 12 55 20

I added some formatting to this number as I think given we are working with large numbers it is confusing otherwise. I also increased the width of this as standard to support numbers in the millions, without the size growing dynamically.

**Comment by Xtoseone** [comment]
@shan8851 could we input numbers manually?

**Comment by shan8851** [comment]
> @shan8851 could we input numbers manually? or slider only?

Hmm I actually viewed this as just a display of the value from slider, but maybe it was intention to be an input. I'll find out from Massimo and finalise

**Review by Xtoseone — CHANGES_REQUESTED** [review]
0 is stay be after begin input

https://user-images.githubusercontent.com/114728833/220294105-945a75c4-41b0-49c2-8fdc-e6da75dcb972.mp4

**Review by Xtoseone — COMMENTED** [review]
we should not be able to enter a number higher than 1 000 000.

https://user-images.githubusercontent.com/114728833/220295151-7022e19a-5ced-4047-947f-30a9a27b5a98.mp4

**Comment by shan8851** [comment]
> we should not be able to enter a number higher than 1 000 000.

hey mate, yes I did think about this, but we have no toast notifications setup inside component lib, so we can add that when in Cielo app, to show a number if they choose something more than max number

**Comment by Xtoseone** [comment]
can we change the number and add a condition: delete 0 if we have a number after 0
EX: user input 08548755 and use the 'Apply' btn. after this the 'Zero' will delete

Скриншот 22-02-2023 153347

**Comment by shan8851** [comment]
> @shan8851  can we change the number and add a condition: delete 0 if we have a number after 0?
> 
> EX: user input 08548755 and use the 'Apply' btn. after this the 'Zero' will delete
> 
> 
> 
> Скриншот 22-02-2023 153347
> 
> 

Yeah with input type=number there is a leading 0, I'll write a function to trim this

**Comment by ArinCantCode** [comment]
Hey @shan8851 couple things:

1. Since we accept string and relay it on being a number can you have a check if `Number.isNaN(num)` throw an error or smth?
2. I think this slider should be more reusable for the future, so any component should be able to open it + the note and label should be dynamic

**Comment by shan8851** [comment]
> Hey @shan8851 couple things:
> 
> 1. Since we accept string and relay it on being a number can you have a check if `Number.isNaN(num)` throw an error or smth?
> 2. I think this slider should be more reusable for the future, so any component should be able to open it + the note and label should be dynamic

hey mate, so we do have a more basic version of slider inside `atoms`, and this one was specific to feed. Do you mean we should have this configuration more reusable with all text etc passed as props?

Yeah so input type=number still returns a string, it does restrict so doing a check for NaN is probably a good idea, do you think we should just handle this with validation like we have for large numbers rather than throw an error

**Pull request merged**
