### PR TITLE
Fe 737

### PR DESCRIPTION
**Pull request by goshatravin**
# Description

Add new component textarea  (https://uniwhales.atlassian.net/browse/FE-737)

---

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:
* Hardware: Android/iphone/macbook/pc/laptop

## Was this feature tested on all the browsers?

- [x] Chrome/Brave
- [] Firefox
- [] Safari 

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Storybook covers all new/pre-existing variations without need to change controls to test it
- [ ] I have upgraded version in package.json
- [x] I have assigned QA and Reviewers
- [x] I have labeled the PR accordingly
- [ ] I have updated time spent in my jira ticket
- [x] Build succeeded

---

### CODE REVIEW

**Comment by Xtoseone** [comment]
not visible on the dark theme, perhaps need to make a contrasting color of the font at once

Скриншот 04-01-2023 092955

**Comment by Xtoseone** [comment]
need to limit the number of characters.

https://user-images.githubusercontent.com/114728833/210514642-854c6ddc-9cf1-47ca-861c-16d4e54aef16.mp4

**Comment by ArinCantCode** [comment]
> need to limit the number of characters.
> 04-01-2023.093145.mp4

tbh limit should be situational depending how its used on frontend i don't think we should enforce it in storybook

**Comment by ArinCantCode** [comment]
@goshatravin how about we also add a "label" above the text field in left side corner that is optional? I think it will be quite common to have it there

**Comment by ArinCantCode** [comment]
@goshatravin any changes you want to add to this one or can i just merge?

**Review by Xtoseone — APPROVED** [review]

**Review by ArinCantCode — APPROVED** [review]

**Pull request merged**
