### PR TITLE
Bugfix/click outside nav

### PR DESCRIPTION
**Pull request by shan8851**
# Description

Adding back in the click outside function on profile icon. This is needed in order to complete this PR - https://uniwhales.atlassian.net/browse/FE-538?atlOrigin=eyJpIjoiZGM0MTk2YmM0YzJjNDNhMzk3NDI0OTJiOWZlMGU5ZGYiLCJwIjoiaiJ9

---

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Was this feature tested on all the browsers?

- [X] Chrome/Brave

# Checklist:

- [X] I have performed a self-review of my code
- [X] My changes generate no new warnings
- [X] Storybook covers all new/pre-existing variations without need to change controls to test it
- [X] I have upgraded version in package.json
- [X] I have assigned QA and Reviewers
- [X] I have labeled the PR accordingly

### CODE REVIEW

**Comment by shan8851** [comment]
I have also added some styles to the modal component as a stop gap until I figure out the best way to use consistent modals throughout the frontend application. So this will add the shadow to all modals for now.

**Comment by ArinCantCode** [comment]
@shan8851 the fix works really nice, but could we make few more improvements?

1. When you scroll the user menu should close or stay where it is i think rather than going with scroll. (closing it is probably better)
2. Close the menu when navbar is clicked (only outside clicks closes it now)

I think that's all we have to do

**Comment by shan8851** [comment]
> @shan8851 the fix works really nice, but could we make few more improvements?
> 
> 1. When you scroll the user menu should close or stay where it is i think rather than going with scroll. (closing it is probably better)
> 2. Close the menu when navbar is clicked (only outside clicks closes it now)
> 
> I think that's all we have to do

Please recheck when you get chance

**Comment by shan8851** [comment]
@ArinCantCode can we get this merged?

**Review by goshatravin — APPROVED** [review]

**Pull request merged**
