### PR TITLE
Fe 1091 improve min usd slider on feed

### PR DESCRIPTION
**Pull request by shan8851**
# Description

This pull request introduces an optional logarithmic scaling feature to the `Slider` component.

Changes:

- Added a new optional prop useLogarithmic.
- Implemented two new utility functions, logScale and inverseLogScale, to handle logarithmic scaling calculations.
- Conditionally applied logarithmic scaling to the slider based on the useLogarithmic prop in the handleSliderChange function.
- Updated the handleSliderChange function to properly synchronize the input field with the slider when using logarithmic scaling.
- Ensured that the input field displays the actual value from the range (between 0 and 10 million) when using logarithmic scaling.

When `useLogarithmic` is enabled, the slider thumb will move more slowly in the early part of the range, providing more precise control over lower values. The slider will continue to behave linearly when the  prop is not provided.

### UX Tradeoff

While the logarithmic scaling provides better control over lower values, there is a trade-off in the user experience. The slider thumb movement might feel less responsive or slower, especially at the lower end of the scale, as the logarithmic scale compresses the lower range values. However, this trade-off allows for more precise control over the lower range values, which was the main goal here.

In the video below we have a rang of 0 to 10million and you can see this UX tradeoff. With the range we want to use for this slider (up to 1million) the effect is not as exaggerated.

https://user-images.githubusercontent.com/39712238/229593504-5e425117-64e8-461d-8071-6b1d86fff511.mp4

---

Fixes # (issue)
[FE-1091](https://uniwhales.atlassian.net/browse/FE-1091?atlOrigin=eyJpIjoiMGNlNGU0MzVhYzAyNDNhYWJhYzE1MTJiZWRkZmUzYmIiLCJwIjoiaiJ9)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:
* Hardware: Android/iphone/macbook/pc/laptop

## Was this feature tested on all the browsers?

- [x] Chrome/Brave
- [ ] Firefox
- [ ] Safari 

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have tested my changes
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Storybook covers all new/pre-existing variations without need to change controls to test it
- [x] I have upgraded version in package.json
- [x] I have assigned QA and Reviewers
- [x] I have labeled the PR accordingly
- [ ] I have updated time spent in my jira ticket
- [ ] Build succeeded

---

## Notes for Devs

[FE-1091]: https://uniwhales.atlassian.net/browse/FE-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Xtoseone** [comment]
just thoughts: if we want to reduce it to 1 000 000, maybe we should make the movement of the slider even smoother, I mean at the end it jumps forward 150-200k
@temurti @shan8851 

https://user-images.githubusercontent.com/114728833/229602120-0bd95f54-4e3a-42ea-8ded-cab1e1202f5e.mp4

**Review by ArinCantCode — APPROVED** [review]

**Comment by temurti** [comment]
@shan8851 let's reduce max to 250k and find the best options for this number

**Comment by Xtoseone** [comment]
@shan8851 maybe we're doing it a little slower?

https://user-images.githubusercontent.com/114728833/229802058-e5882d71-2b87-4152-9bce-d19b51e7b44f.mp4

**Comment by shan8851** [comment]
@Xtoseone just fyi @temurti approved the latest implementation. So @ArinCantCode @goshatravin if you guys are happy with the code can we get this approved and released and I can update properly on the feed page

**Review by Xtoseone — APPROVED** [review]

**Review by temurti — APPROVED** [review]

**Review by ArinCantCode — APPROVED** [review]

**Pull request merged**
