### PR TITLE
Fe 567/582/587 modals and messaging

### PR DESCRIPTION
**Pull request by shan8851**
# Description

Related JIRA tickets linked below. This is the comp lib changes for modals, inputs and dropdowns. This **WILL** require quite a few changes in the frontend application, so we need a plan before merging this.

### Modals

Modals will now no longer accept `children` and instead will take `mainContent` and optionally `aditionalContent`, when a double modal is required. Interface is like so:

```
export type ModalBaseProps = {
  mainContent: ReactElement
  headerText: string
  headerIcon: ReactElement
  modalVariant: 'single' | 'double'
  closeFn?: MouseEventHandler<HTMLDivElement | HTMLButtonElement>
  additionalContent?: ReactElement
  showAdditionalContent?: boolean
};
```

And can be used like so:

```
    <ModalBase
      closeFn={closeFn}
      headerText="Double Modal"
      headerIcon={<StarIcon />}
      modalVariant="double"
      mainContent={mainContent}
      additionalContent={additionalContent}
      showAdditionalContent={showMore}
    />
```

### Inputs

Inputs now have many different states, so to help manage this I have created an `inputState` prop that works like so:

```
export interface InputState {
  status: 'default' | 'disabled' | 'error' | 'invalid' | 'valid' | 'exception' | 'help'
  message: string;
}
```

### Dropdowns

Missing hover and disabled states added to dropdown

### In Dashboard Messages

PR contains two types of In Dashboard Messages

#### Dash Message One

```
export interface DashMessageOneProps {
  title: string;
  message: string;
  night: boolean;
  secondaryMessage?: string;
}
```

and can be used like so:

```
    <DashMessageOne
      night={night}
      title="Dashboard Under Maintenance"
      message="This dashboard is still under contrsuction or is going through maintenance. "
      secondaryMessage="Contact us if you need more support"
    />
```

#### Dash Message Two

```
export interface DashMessageTwoProps {
  title: string;
  message: string;
  buttonText: string;
  onClick: () => void;
  night: boolean;
  buttonIcon?: ReactElement
}
```

and can be used like so:

```
    <DashMessageTwo
      night={night}
      title="Connect Your Wallet"
      message="You must be a Pro or Whale member to see this page. Connect your verified wallet to see all the latest content and data"
      buttonText="Get UWL"
      buttonIcon={<IconWrapper cursor="pointer" icon={<UniWhales />} />}
    />
```

### SocialButton Group

Component for social button group that accepts `onTelgramClick` and `onTwitterClick` and can be used like so:

```
      <SocialButtonGroup
        onTelegramClick={() => {}}
        onTwitterClick={() => {}}
      />
```

---

Fixes # (issue)
https://uniwhales.atlassian.net/browse/FE-567?atlOrigin=eyJpIjoiOWNmMDg4YzcyOTRmNDkzZGFjYmU0MWMzZGIyNTZmM2IiLCJwIjoiaiJ9

https://uniwhales.atlassian.net/browse/FE-582?atlOrigin=eyJpIjoiYTQ1ZjFkYzhhZTg2NDIyMjk1YTcyOGQ5OGVkYjUwMjUiLCJwIjoiaiJ9

https://uniwhales.atlassian.net/browse/FE-587?atlOrigin=eyJpIjoiNzczMzBmN2FkNjE2NGVmODk1ZDVkMzQxN2I3MjQ2OWEiLCJwIjoiaiJ9

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:
* Hardware: Android/iphone/macbook/pc/laptop

## Was this feature tested on all the browsers?

- [X] Chrome/Brave
- [X] Firefox
- [] Safari 

# Checklist:

- [X] I have performed a self-review of my code
- [ ] I have tested my changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] Storybook covers all new/pre-existing variations without need to change controls to test it
- [X] I have upgraded version in package.json
- [X] I have assigned QA and Reviewers
- [X] I have labeled the PR accordingly
- [X] I have updated time spent in my jira ticket
- [ ] Build succeeded

---

### CODE REVIEW

**Comment by Xtoseone** [comment]
@shan8851 look at it, please.  Dashboard messages (Dash Messages One and Two) have different sizes on Figma and Storybook
Скриншот 14-11-2022 122156

**Comment by Xtoseone** [comment]
@shan8851 
Скриншот 14-11-2022 141737

**Review by Xtoseone — APPROVED** [review]

**Review by goshatravin — APPROVED** [review]

**Review by ArinCantCode — CHANGES_REQUESTED** [review]

**Comment by goshatravin** [comment]
@shan8851 
Screenshot 2022-11-16 at 10 20 03
check this scrolling lines

**Review by goshatravin — CHANGES_REQUESTED** [review]
@shan8851 i think something with overflow: scroll, since i can see all scrolling lines

**Review by ArinCantCode — APPROVED** [review]

**Pull request merged**
